apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "robo-services.receiverName" . }}
  namespace: {{ include "robo-services.namespace" . }}
  labels:
    {{- include "robo-services.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.receiver.replicaCount }}
  selector:
    matchLabels:
      {{- include "robo-services.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "robo-services.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "robo-services.receiverName" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: udp-ingest
              containerPort: {{ .Values.service.targetPort }}
              protocol: {{ .Values.service.protocol }}
          envFrom:
            - configMapRef:
                name: {{ include "robo-services.configMapName" . }}
            - secretRef:
                name: {{ include "robo-services.secretName" . }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
