{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ include "robo-services.namespace" . }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence false
    log_dest stdout
{{- end }}
