{{- if .Values.mosquitto.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mosquitto.name }}
  namespace: {{ include "robo-services.namespace" . }}
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mosquitto
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mosquitto
          image: {{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}
          imagePullPolicy: {{ .Values.mosquitto.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
          resources: {{- toYaml .Values.mosquitto.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
{{- end }}
