apiVersion: v1
kind: Service
metadata:
  name: {{ include "robo-services.receiverName" . }}
  namespace: {{ include "robo-services.receiverNamespace" . }}
  labels:
    {{- include "robo-services.receiverLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "robo-services.receiverSelectorLabels" . | nindent 4 }}
  ports:
    - name: udp-ingest
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
