apiVersion: v1
kind: Secret
metadata:
  name: kreceiver-secret
  namespace: robo-services
type: Opaque
stringData:
  KRECEIVER_IGGY_CONNECTION_STRING: "iggy+tcp://iggy:replace-me@iggy.pub-sub.svc.cluster.local:8090"
