apiVersion: v1
kind: Service
metadata:
  name: kreceiver
  namespace: robo-services
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.70
spec:
  type: LoadBalancer
  selector:
    app: kreceiver
  ports:
    - name: udp-ingest
      protocol: UDP
      port: 5514
      targetPort: 5514
